### ISSUE TITLE
Support for configs

### ISSUE THREAD

**Issue by johnnyasantoss** [Plazide/local-ai-code-completion#2]
Hello, I just found your extension, and it looks like it could be improved by having settings to control how the model runs, how big the context is, and other configs.

**Comment by johnnyasantoss** [comment]
This other extension allows configurations but their goal seems to be different https://github.com/rjmacarthy/twinny

I'll try to take a look at the code and see if I can create a PR

**Comment by chj-web** [comment]
Hey,

Actually, I merged a PR the other day that added some configuration options #1 

That should be a good starting point for you.

**Comment by johnnyasantoss** [comment]
@Plazide when I created the PR the latest version on the vscode store was still outdated. Will take a look. The extension could have it's own log output as well, to help debug issues. Will take a look on how to do that this week.

**Comment by chj-web** [comment]
@johnnyasantoss 

I haven't had time to upload the new version to the vscode marketplace yet, but I will let you know when it's up.

Adding a log output would be great! Let me know if there is anything I can help you with.

**Comment by chj-web** [comment]
@johnnyasantoss I just updated the extension with the new config options. You should be able to find it by opening vscode settings and searching for "local ai".

**Comment by johnnyasantoss** [comment]
I have the changes on a local branch with a bunch of improvements. Will try to create a PR
