### ISSUE TITLE
Failed to start Ollama server.

### ISSUE THREAD

**Issue by merolaika** [Plazide/local-ai-code-completion#6]
in visual studio code give this: Failed to start Ollama server.

Ollama is running and have a model

**Comment by chj-web** [comment]
Hello,

I've tried to reproduce this, but to no success.

Could you share some additional details about your environment?

- What Ollama version are you running? Check by running `ollama --version`
- What VSCode version are you running? Check by running `code --version`
- What is the full output of the extension? 
![image](https://github.com/Plazide/local-ai-code-completion/assets/20641118/bd3ca660-ec45-482e-853a-1853be6906d1)

**Comment by merolaika** [comment]
Hello sir, i use;

`ollama version is 0.1.25`

and

```
code --version
1.85.1
0ee08df0cf4527e40edc9aa28f4b5bd38bbff2b2
x64
```

**Comment by chj-web** [comment]
@merolaika Are you on Windows, Linux, or macOS?

**Comment by noname-oni** [comment]
@Plazide I'm on Windows facing this

**Comment by merolaika** [comment]
> @merolaika Are you on Windows, Linux, or macOS?

Hello, im on windows too

**Comment by chj-web** [comment]
@merolaika @cogscides It seems this is related to our check to see if Ollama is running. The method we are using to do this does not seem to work on the Windows version of Ollama. 

Still need to investigate further, but will update when I have more info.

**Comment by chj-web** [comment]
@merolaika I see you closed this issue. Did you find a solution?

**Comment by merolaika** [comment]
yep its okey just reinstall ollama and its working dont understand :))
